### ISSUE TITLE
Script bedarf Ergänzungen

### ISSUE THREAD

**Issue by jjsarton** [freifunk-suedpfalz/ffsuedpfalz-fwbuilder#4]
Das Script funktioniert nicht wie erwünscht. Die Erzeugung der Firmware endet immer mit Fehlern.

**Comment by holymoly** [comment]
kannst du die Fehler posten?

**Comment by kemisolon** [comment]
Für Fedora benötigt man folgende Pakete.
git make cmake gcc gcc-c++ unzip ncurses-devel zlib-devel subversion gawk bzip2 openssl-devel wget curl pkgconfig libuecc doxygen patch perl-Thread-Queue python ecdsautils

Bei Debian /Ubuntu:
git make cmake gcc g++ unzip libncurses5-dev zlib1g-dev subversion gawk bzip2 libssl-dev wget curl pkg-config

**Comment by holymoly** [comment]
kann man den check erweitern?

**Comment by kemisolon** [comment]
Ja ist in Arbeit. Jedoch heißen die Pakete bei jedem Betriebssystem anders.

**Comment by jjsarton** [comment]
Wünschenswert wäre dass die site Dateien entsprechend Gluon Version heruntergeladen wird, die Probleme lagen wahrscheinlich daran-
